Te4mmerge
david-fisher/320-F21-Track-1 pull request #86
Opened 2021-12-08 18:52 UTC by userazhao

te4m merge

2021-12-08 19:19 UTC, tomking commented
@userazhao So this branch is comprised of the files from the te4mdemo branch copied into the te4m branch? Just making sure I am following here.

2021-12-08 19:22 UTC, tomking commented
Will we want the demo file on main? Additionally, if we are using Team Team's objects/code for some of these things (such as Cards) do we want our code for them on main if it won't be used?

2021-12-08 19:30 UTC, tomking requested changes
There are still some reviews and edits that need to be made in regards to which team's object are being used. Myself, @imnnos and @kunjdedhia will be on Zoom this evening and will review/edit this branch then update this pull request. Until then I would suggest not merging this.

2021-12-10 19:57 UTC, imnnos approved these changes

2021-12-10 19:58 UTC, tomking approved these changes

2021-12-10 19:59 UTC, merged